### ISSUE TITLE
Connection to PostgreSQL using docker sqitch, local user with ID 1000 doesn't exist

### ISSUE THREAD

**Issue by arochadaniel** [sqitchers/docker-sqitch#13]
Hi! I'm building my backend with multiple docker services, one of them is migrations in which I'm using sqitch. My Dockerfile is:

```
FROM hpo/postgres-client as psql-build

# Create workdir
RUN mkdir -p /migrations

# Stage to install sqitch
FROM sqitch/sqitch:latest as sqitch

COPY --from=psql-build /usr/bin/psql /usr/bin

WORKDIR /migrations
COPY . /migrations

# Set up environment, entrypoint, and default command.
ENV LESS=-R LC_ALL=C.UTF-8 LANG=C.UTF-8 SQITCH_EDITOR=vim SQITCH_PAGER=less
USER sqitch
ENTRYPOINT ["/bin/sqitch"]
CMD ["help"]
```

The postgres client in the first line is a base image that I built for many of the services to save space. Then sqitch installs fine, I can init a project, add migrations, but, when I have to run those migrations I hit a wall. I made this script to run them:

```
#!/bin/bash

docker-compose run -u `id -u $USER` migrations $@
```

But, for example, if I run `./sqitch.sh deploy` or `./sqitch.sh revert` or `./sqitch.sh verify` it tells me `local user with ID 1000 does not exist` I know this is caused by the user inside the Docker container, basically, there is no user with id 1000.

I tried creating one directly on the Dockerfile and then using it with the `USER` command near the end of the file, didn't work, getting the same error. 

I checked your Dockerfile an saw you create a sqitch user for the image with id 1024, tried using it too changing the user id in the sqitch.sh script to 1024, didn't work either. 

I thought that maybe the sqitch.sh script is too basic, and maybe there was something I wasn't considering, so I used the script you provide here, but I got the same error

Finally, I started reading documentation and tried to set and environment variable `SQITCH_USERNAME` in a local var.env file which is set to be used by the docker-compose file, didn't work. 

Hope you can help me! This is my docker-compose.yml file: 

```
version: "3"
services:
  # Migrations service
  migrations:
    build: .
    volumes:
      - ./:/migrations
      - ~/.sqitch/:/home/.sqitch
    environment:
      - ./var.env 
    networks:
      - internal
    external_links:
      - hpo-database:db

networks:
  internal:
    external: true
```
